language: c

compiler:
    - clang
    - gcc

install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update
    - sudo apt-get install -y criterion-dev

script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make
    - ./test
